services:
  postgres_template: &postgres
    build: ${PATH_TO_SOURCE}
    tty: true
    cgroup: private
    volumes:
      - ${PATH_TO_SOURCE}:/var/lib/postgres_src
      - ./docker-scripts:/scripts
      - ./cluster-bin:/var/lib/postgresql
    labels:
      chaos: true
  
  master: &default_conf
    <<: *postgres
    cpu_count: 2
    blkio_config:
#      weight_device:
#        - path: /dev/nvme0n1p2
#          weight: 1000
      device_read_bps:
        - path: /dev/nvme0n1
          rate: '1000mb'
      device_write_bps:
        - path: /dev/nvme0n1
          rate: '1200mb'
      device_read_iops:
        - path: /dev/nvme0n1
          rate: 10000
      device_write_iops:
        - path: /dev/nvme0n1
          rate: 10000
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
        reservations:
          cpus: '1.5'
          memory: 2.5G
    ports:
      - 5432:5432
  
  replicas:
    <<: *default_conf
    ports:
      - target: 5432
        published: ${START_PORT}-${END_PORT}
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: ${COUNT_REPLICAS}
  
  pumba_latency:
    image: ghcr.io/alexei-led/pumba:latest
    container_name: pumba_latency
    depends_on:
      - master
      - replicas
    command: >
        --log-level debug
        --interval 6s
        netem --duration 5s
        delay --time 25 --jitter 5 --correlation 80
        re2:^pgrepmonitor
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - NET_ADMIN
    restart: unless-stopped